Part 1
amly1233/taipei-day-trip-website pull request #2
Opened 2021-04-23 11:02 UTC by amly1233

呂晧瑜

2021-04-23 20:40 UTC, cwpeng requested changes
請提供可以測試，已經上線的 API 網址哦 ~

2021-04-28 09:09 UTC, cwpeng requested changes
1.
我們的 page 是從 0 開始算的哦。
2.
關鍵字搜尋的概念，應該是你搜尋了某個關鍵字之後，例如【臺北】，假設得到 20 筆資料，那麼第 0 頁就應該有 12 筆，第 1 頁則有 8 筆，沒有第 2 頁。你可以使用 LIMIT 語句來完成這樣的資料分頁，請調整你的關鍵字搜尋相關的邏輯。

2021-04-28 14:56 UTC, cwpeng approved these changes
OK. Good Changes. Keep Going. ~

2021-05-09 15:05 UTC, amly1233 commented
老師，很遲交的Part 2 作業
http://3.141.94.145:3000/
再幫我看一下，謝謝～～
呂晧瑜

2021-05-09 16:26 UTC, cwpeng approved these changes
辛苦了，看起來沒太大問題，這樣就可以，繼續加油嘍 :)

記得 Review Approve 之後，要 Merge Pull Request，讓確定被看過的程式能放到你的 main 分支上。

2021-05-10 01:41 UTC, merged